kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/vmware/octant

steps:
  - name: frontend
    image: circleci/node:10.15.3-browsers
    user: node
    commands:
      - cd web
      - npm ci
      - npm run-script build
      - npm run test:headless
  - name: backend
    image: golang:1.12
    commands:
      - make go-install
      - make test
      - go generate ./web
      - make vet
  - name: build
    image: golang:1.12
    environment:
      CGO_ENABLED: 0
    commands:
      - make octant-dev
    depends_on:
    - frontend
    - backend
  - name: release
    when:
      event:
        - tag
    image: goreleaser/goreleaser:v0.110-cgo
    commands:
      - /bin/bash ci/drone-deploy.sh
    depends_on:
    - build
