---
kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/vmware/octant

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
    when:
      event:
      - tag
  - name: frontend
    image: sfoo/node-chrome:0.0.1
    commands:
      - cd web
      - npm ci
      - npm run-script build
      - npm run test:headless
  - name: backend
    image: golang:1.12
    environment:
      GOFLAGS: -mod=vendor
      GO111MODULE: on
    commands:
      - make go-install
      - make test
      - go generate ./web
      - make vet
    depends_on:
    - frontend
  - name: build
    image: golang:1.12
    environment:
      CGO_ENABLED: 0
    commands:
      - make octant-dev
    depends_on:
    - frontend
    - backend
  - name: release
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      event:
        - tag
    image: goreleaser/goreleaser:v0.110-cgo
    commands:
      - /bin/bash ci/drone-deploy.sh
    depends_on:
    - build
---
kind: signature
hmac: d12ab7e7c46cbea63d6dd35ee01da089c277b948fcdaa60d78a97049bd80d579

...
