apiVersion: apps/v1
kind: Deployment
metadata:
  name: clustereye
  labels:
    app: clustereye
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clustereye
  template:
    metadata:
      labels:
        app: clustereye
    spec:
      containers:
      - name: clustereye
        image: clustereye
        command: ["/clustereye"]
        args: ["-v", "--kubeconfig", "/kube/dev-dash-kubeconfig.yaml"]
        ports:
        - containerPort: 7777
        env:
          - name: CLUSTEREYE_LISTENER_ADDR
            value: 0.0.0.0:7777
          - name: CLUSTEREYE_DISABLE_OPEN_BROWSER
            value: "1"
        volumeMounts:
          - name: kubeconfig
            mountPath: /kube/
      volumes:
        - name: kubeconfig
          secret:
            secretName: clustereye-kubeconfig
            defaultMode: 256
